-d G:\_Programming\_DOCS\Schematics\MyModular\FPGA\VGA\impl\gwsynthesis\fpga_project.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst G:\_Programming\_DOCS\Schematics\MyModular\FPGA\VGA\src\fpga_project.cst
-cfg G:\_Programming\_DOCS\Schematics\MyModular\FPGA\VGA\impl\pnr\device.cfg
-sdc G:\_Programming\_DOCS\Schematics\MyModular\FPGA\VGA\src\fpga_project.sdc
-bit
-tr
-ph
-oc
-timing
-cst_error
-no_cst_warning
