                ORG $7A00

; SMB: changed to use the dg pseudo-op, was all DB statements

CharSet         dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........

                dg ..X.....
                dg ........
                dg X...X...
                dg .X...X..
                dg ..X...X.
                dg ...X...X
                dg ....X...
                dg .....X..

                dg ...X....
                dg ....X...
                dg .....X..
                dg X.....X.
                dg .X.....X
                dg ..X.....
                dg ...X....
                dg ....X...

                dg ....X...
                dg .....X..
                dg ......X.
                dg .......X
                dg X.......
                dg .X......
                dg ..X.....
                dg ...X....

                dg .....X..
                dg ......X.
                dg .......X
                dg ........
                dg ........
                dg X.......
                dg .X......
                dg ..X.....

                dg ......X.
                dg .......X
                dg ........
                dg ........
                dg ........
                dg ........
                dg X.......
                dg .X......

                dg .......X
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg X.......

                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg .XX.....
                dg .XX.....
                dg ........

                dg ........
                dg ........
                dg ........
                dg ........
                dg .XX.....
                dg X..X....
                dg X..X....
                dg .XX.....

                dg ........
                dg ........
                dg ........
                dg ........
                dg XXXX....
                dg X..X....
                dg X..X....
                dg XXXX....

                dg ........
                dg ........
                dg ........
                dg ........
                dg .XX.....
                dg XXXX....
                dg XXXX....
                dg .XX.....

                dg ........
                dg ........
                dg ........
                dg ........
                dg XXXX....
                dg XXXX....
                dg XXXX....
                dg XXXX....

                dg ........
                dg ........
                dg ........
                dg XX......
                dg XX......
                dg ........
                dg ........
                dg ........

                dg ........
                dg ........
                dg .XX.....
                dg X..X....
                dg X..X....
                dg .XX.....
                dg ........
                dg ........

                dg ........
                dg ........
                dg XXXX....
                dg X..X....
                dg X..X....
                dg XXXX....
                dg ........
                dg ........

                dg ........
                dg ........
                dg .XX.....
                dg XXXX....
                dg XXXX....
                dg .XX.....
                dg ........
                dg ........

                dg ........
                dg ........
                dg XXXX....
                dg XXXX....
                dg XXXX....
                dg XXXX....
                dg ........
                dg ........

                dg ...XX...
                dg ...XX...
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........

                dg ...XX...
                dg ..X..X..
                dg ..X..X..
                dg ...XX...
                dg ........
                dg ........
                dg ........
                dg ........

                dg ..XXXX..
                dg ..X..X..
                dg ..X..X..
                dg ..XXXX..
                dg ........
                dg ........
                dg ........
                dg ........

                dg ...XX...
                dg ..XXXX..
                dg ..XXXX..
                dg ...XX...
                dg ........
                dg ........
                dg ........
                dg ........

                dg ..XXXX..
                dg ..XXXX..
                dg ..XXXX..
                dg ..XXXX..
                dg ........
                dg ........
                dg ........
                dg ........

                dg XXXXXXXX
                dg ........
                dg ........
                dg XXXXXXXX
                dg XXXXXXXX
                dg ........
                dg ........
                dg XXXXXXXX

                dg X..XX..X
                dg X..XX..X
                dg X..XX..X
                dg X..XX..X
                dg X..XX..X
                dg X..XX..X
                dg X..XX..X
                dg X..XX..X

                dg ........
                dg ........
                dg XXX.....
                dg ...X....
                dg ....X...
                dg XX...X..
                dg ..X..X..
                dg ..X..X..

                dg ........
                dg ........
                dg XXXXXXXX
                dg ........
                dg ........
                dg XX....XX
                dg ..X..X..
                dg ..X..X..

                dg ..X..X..
                dg ..X..X..
                dg XX...X..
                dg .....X..
                dg .....X..
                dg XX...X..
                dg ..X..X..
                dg ..X..X..

                dg ........
                dg ........
                dg X.......
                dg X.......
                dg X.......
                dg X.......
                dg ........
                dg ........

                dg ..XXXX..
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........

                dg ...XX...
                dg ...XX...
                dg ..XXXX..
                dg XXXXXXXX
                dg XXXXXXXX
                dg XXXXXXXX
                dg XXXXXXXX
                dg XXXXXXXX

                dg ........
                dg ........
                dg ........
                dg XXXXX...
                dg XXXXXX..
                dg XXXXXX..
                dg XXXXXX..
                dg XXXXXX..

                dg XXXXX...
                dg XX......
                dg X.X.....
                dg X..X....
                dg X...X...
                dg .....X..
                dg ......X.
                dg .......X

                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........

                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ........
                dg ...X....
                dg ........

                dg ..X.X...
                dg ..X.X...
                dg ..X.X...
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........

                dg ..X.X...
                dg ..X.X...
                dg .XXXXX..
                dg ..X.X...
                dg .XXXXX..
                dg ..X.X...
                dg ..X.X...
                dg ........

                dg ...X....
                dg ..XXXX..
                dg .X.X....
                dg ..XXX...
                dg ...X.X..
                dg .XXXX...
                dg ...X....
                dg ........

                dg .XX.....
                dg .XX..X..
                dg ....X...
                dg ...X....
                dg ..X.....
                dg .X..XX..
                dg ....XX..
                dg ........

                dg ..X.....
                dg .X.X....
                dg .X.X....
                dg ..X.....
                dg .X.X.X..
                dg .X..X...
                dg ..XX.X..
                dg ........

                dg ...X....
                dg ...X....
                dg ...X....
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........

                dg ...X....
                dg ..X.....
                dg .X......
                dg .X......
                dg .X......
                dg ..X.....
                dg ...X....
                dg ........

                dg ...X....
                dg ....X...
                dg .....X..
                dg .....X..
                dg .....X..
                dg ....X...
                dg ...X....
                dg ........

                dg ...X....
                dg .X.X.X..
                dg ..XXX...
                dg ...X....
                dg ..XXX...
                dg .X.X.X..
                dg ...X....
                dg ........

                dg ........
                dg ...X....
                dg ...X....
                dg .XXXXX..
                dg ...X....
                dg ...X....
                dg ........
                dg ........

                dg ........
                dg ........
                dg ........
                dg ........
                dg ...X....
                dg ...X....
                dg ..X.....
                dg ........

                dg ........
                dg ........
                dg ........
                dg .XXXXX..
                dg ........
                dg ........
                dg ........
                dg ........

                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ...X....
                dg ........

                dg ........
                dg .....X..
                dg ....X...
                dg ...X....
                dg ..X.....
                dg .X......
                dg ........
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X..XX..
                dg .X.X.X..
                dg .XX..X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg ...X....
                dg ..XX....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ..XXX...
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .....X..
                dg ...XX...
                dg ..X.....
                dg .X......
                dg .XXXXX..
                dg ........

                dg .XXXXX..
                dg .....X..
                dg ....X...
                dg ...XX...
                dg .....X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg ....X...
                dg ...XX...
                dg ..X.X...
                dg .X..X...
                dg .XXXXX..
                dg ....X...
                dg ....X...
                dg ........

                dg .XXXXX..
                dg .X......
                dg .XXXX...
                dg .....X..
                dg .....X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg ...XXX..
                dg ..X.....
                dg .X......
                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg .XXXXX..
                dg .....X..
                dg ....X...
                dg ...X....
                dg ..X.....
                dg ..X.....
                dg ..X.....
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X...X..
                dg ..XXX...
                dg .X...X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X...X..
                dg ..XXXX..
                dg .....X..
                dg ....X...
                dg .XXX....
                dg ........

                dg ........
                dg ........
                dg ...X....
                dg ........
                dg ...X....
                dg ........
                dg ........
                dg ........

                dg ........
                dg ........
                dg ...X....
                dg ........
                dg ...X....
                dg ...X....
                dg ..X.....
                dg ........

                dg ....X...
                dg ...X....
                dg ..X.....
                dg .X......
                dg ..X.....
                dg ...X....
                dg ....X...
                dg ........

                dg ........
                dg ........
                dg .XXXXX..
                dg ........
                dg .XXXXX..
                dg ........
                dg ........
                dg ........

                dg ..X.....
                dg ...X....
                dg ....X...
                dg .....X..
                dg ....X...
                dg ...X....
                dg ..X.....
                dg ........

                dg ..XXX...
                dg .X...X..
                dg ....X...
                dg ...X....
                dg ...X....
                dg ........
                dg ...X....
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X.X.X..
                dg .X.XXX..
                dg .X.XX...
                dg .X......
                dg ..XXXX..
                dg ........

                dg ...X....
                dg ..X.X...
                dg .X...X..
                dg .X...X..
                dg .XXXXX..
                dg .X...X..
                dg .X...X..
                dg ........

                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .XXXX...
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X......
                dg .X......
                dg .X......
                dg .X...X..
                dg ..XXX...
                dg ........

                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .XXXX...
                dg ........

                dg .XXXXX..
                dg .X......
                dg .X......
                dg .XXXX...
                dg .X......
                dg .X......
                dg .XXXXX..
                dg ........

                dg .XXXXX..
                dg .X......
                dg .X......
                dg .XXXX...
                dg .X......
                dg .X......
                dg .X......
                dg ........

                dg ..XXXX..
                dg .X......
                dg .X......
                dg .X......
                dg .X..XX..
                dg .X...X..
                dg ..XXXX..
                dg ........

                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .XXXXX..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ........

                dg ..XXX...
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ..XXX...
                dg ........

                dg .....X..
                dg .....X..
                dg .....X..
                dg .....X..
                dg .....X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg .X...X..
                dg .X..X...
                dg .X.X....
                dg .XX.....
                dg .X.X....
                dg .X..X...
                dg .X...X..
                dg ........

                dg .X......
                dg .X......
                dg .X......
                dg .X......
                dg .X......
                dg .X......
                dg .XXXXX..
                dg ........

                dg .X...X..
                dg .XX.XX..
                dg .X.X.X..
                dg .X.X.X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ........

                dg .X...X..
                dg .X...X..
                dg .XX..X..
                dg .X.X.X..
                dg .X..XX..
                dg .X...X..
                dg .X...X..
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .XXXX...
                dg .X......
                dg .X......
                dg .X......
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X.X.X..
                dg .X..X...
                dg ..XX.X..
                dg ........

                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .XXXX...
                dg .X.X....
                dg .X..X...
                dg .X...X..
                dg ........

                dg ..XXX...
                dg .X...X..
                dg .X......
                dg ..XXX...
                dg .....X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg .XXXXX..
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ........

                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ..X.X...
                dg ...X....
                dg ........

                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X.X.X..
                dg .X.X.X..
                dg .XX.XX..
                dg .X...X..
                dg ........

                dg .X...X..
                dg .X...X..
                dg ..X.X...
                dg ...X....
                dg ..X.X...
                dg .X...X..
                dg .X...X..
                dg ........

                dg .X...X..
                dg .X...X..
                dg ..X.X...
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ........

                dg .XXXXX..
                dg .....X..
                dg ....X...
                dg ...X....
                dg ..X.....
                dg .X......
                dg .XXXXX..
                dg ........

                dg .XXXXX..
                dg .XX.....
                dg .XX.....
                dg .XX.....
                dg .XX.....
                dg .XX.....
                dg .XXXXX..
                dg ........

                dg ........
                dg .X......
                dg ..X.....
                dg ...X....
                dg ....X...
                dg .....X..
                dg ........
                dg ........

                dg .XXXXX..
                dg ....XX..
                dg ....XX..
                dg ....XX..
                dg ....XX..
                dg ....XX..
                dg .XXXXX..
                dg ........

                dg ...X....
                dg ..XXX...
                dg .X.X.X..
                dg ...X....
                dg ...X....
                dg ...X....
                dg ........
                dg ........

                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg .XXXXX..
                dg ........

                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........
                dg ........

                dg ........
                dg ........
                dg ..XX.X..
                dg .X..XX..
                dg .X...X..
                dg .X..XX..
                dg ..XX.X..
                dg ........

                dg .X......
                dg .X......
                dg .X.XX...
                dg .XX..X..
                dg .X...X..
                dg .XX..X..
                dg .X.XX...
                dg ........

                dg ........
                dg ........
                dg ..XXXX..
                dg .X......
                dg .X......
                dg .X......
                dg ..XXXX..
                dg ........

                dg .....X..
                dg .....X..
                dg ..XX.X..
                dg .X..XX..
                dg .X...X..
                dg .X..XX..
                dg ..XX.X..
                dg ........

                dg ........
                dg ........
                dg ..XXX...
                dg .X...X..
                dg .XXXXX..
                dg .X......
                dg ..XXX...
                dg ........

                dg ....X...
                dg ...X....
                dg ...X....
                dg ..XXX...
                dg ...X....
                dg ...X....
                dg ...X....
                dg ........

                dg ........
                dg ........
                dg ..XXXX..
                dg .X...X..
                dg .X..XX..
                dg ..XX.X..
                dg .....X..
                dg ..XXX...

                dg .X......
                dg .X......
                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ........

                dg ........
                dg ...X....
                dg ........
                dg ..XX....
                dg ...X....
                dg ...X....
                dg ..XXX...
                dg ........

                dg ........
                dg ....X...
                dg ........
                dg ....X...
                dg ....X...
                dg ....X...
                dg ....X...
                dg ..XX....

                dg .X......
                dg .X......
                dg .X..X...
                dg .X.X....
                dg .XXX....
                dg .X..X...
                dg .X...X..
                dg ........

                dg ..XX....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ...X....
                dg ..XXX...
                dg ........

                dg ........
                dg ........
                dg .XX.X...
                dg .X.X.X..
                dg .X.X.X..
                dg .X.X.X..
                dg .X.X.X..
                dg ........

                dg ........
                dg ........
                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ........

                dg ........
                dg ........
                dg ..XXX...
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ..XXX...
                dg ........

                dg ........
                dg ........
                dg .XXXX...
                dg .X...X..
                dg .X...X..
                dg .XXXX...
                dg .X......
                dg .X......

                dg ........
                dg ........
                dg ..XXXX..
                dg .X...X..
                dg .X...X..
                dg ..XXXX..
                dg .....X..
                dg .....X..

                dg ........
                dg ........
                dg .X.XX...
                dg .XX.....
                dg .X......
                dg .X......
                dg .X......
                dg ........

                dg ........
                dg ........
                dg ..XXXX..
                dg .X......
                dg ..XXX...
                dg .....X..
                dg .XXXX...
                dg ........

                dg ........
                dg ...X....
                dg .XXXXX..
                dg ...X....
                dg ...X....
                dg ...X....
                dg ....XX..
                dg ........

                dg ........
                dg ........
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg ..XXXX..
                dg ........

                dg ........
                dg ........
                dg .X...X..
                dg .X...X..
                dg ..X.X...
                dg ..X.X...
                dg ...X....
                dg ........

                dg ........
                dg ........
                dg .X...X..
                dg .X...X..
                dg .X...X..
                dg .X.X.X..
                dg ..X.X...
                dg ........

                dg ........
                dg ........
                dg .X...X..
                dg ..X.X...
                dg ...X....
                dg ..X.X...
                dg .X...X..
                dg ........

                dg ........
                dg ........
                dg ..X..X..
                dg ..X..X..
                dg ..X..X..
                dg ..XXXX..
                dg .....X..
                dg ..XXX...

                dg ........
                dg ........
                dg .XXXXX..
                dg ....X...
                dg ...X....
                dg ..X.....
                dg .XXXXX..
                dg ........

                dg ....XX..
                dg ...X....
                dg ...X....
                dg ..X.....
                dg ...X....
                dg ...X....
                dg ....XX..
                dg ........

                dg ........
                dg ...X....
                dg ...X....
                dg ........
                dg ........
                dg ...X....
                dg ...X....
                dg ........

                dg .XX.....
                dg ...X....
                dg ...X....
                dg ....X...
                dg ...X....
                dg ...X....
                dg .XX.....
                dg ........

                dg ........
                dg ...X....
                dg ........
                dg .XXXXX..
                dg ........
                dg ...X....
                dg ........
                dg ........

                dg ........
                dg ........
                dg .....X..
                dg ..XXX...
                dg .X......
                dg ........
                dg ........
                dg ........

